### ISSUE TITLE
DPMS disabled, yet ON

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/CachyOS-Settings#100]
Hi,

DPMS is known for it's black screen issues and more.

While checking with with xset, it shows disabled, yet On in another way. Maybe xset are for X11 only?

```
nu ❯ xset -q | grep DPMS
DPMS (Display Power Management Signaling):
  Server does not have the DPMS Extension

nu ❯ cat /sys/class/drm/card0-DP-2/dpms | to text
On
```

**Comment by 1Naim** [comment]
> Maybe xset are for X11 only

It's in the name.

**Comment by dougg0k** [comment]
?? Sure, point were finding out whether dpms are actually ON or not, and find a way to disable it, if so.

**Comment by 1Naim** [comment]
I don't think you understand what DPMS is. To oversimplify, it's just your screen. So disabling DPMS would turn off the screen which I don't think is what you want. To illustrate

```sh
kscreen-doctor --dpms off
```

**Comment by dougg0k** [comment]
`Display Power Management Signaling (DPMS) enables power saving behaviour of monitors`

On popOS, I disabled it to fix black screen issues.

**Comment by 1Naim** [comment]
Fundamentally, the implementation of DPMS in X11 and other operating systems (wayland included) is different. in X11, DPMS is fully implemented in the spec that VESA provides. However, due to lack of details from the standard, wayland and other OS does not implement VESA's DPMS.

**Comment by dougg0k** [comment]
Right, then why it would report as `On`?

**Comment by 1Naim** [comment]
Because the screen is on.

**Comment by dougg0k** [comment]
Yeah. 

```
# Turn off
busctl --user set-property org.gnome.Mutter.DisplayConfig /org/gnome/Mutter/DisplayConfig org.gnome.Mutter.DisplayConfig PowerSaveMode i 1

# Turn on
busctl --user set-property org.gnome.Mutter.DisplayConfig /org/gnome/Mutter/DisplayConfig org.gnome.Mutter.DisplayConfig PowerSaveMode i 1
```
