### ISSUE TITLE
feature suggestion: ansible playbook

### ISSUE THREAD

**Issue by stefangweichinger** [CachyOS/CachyOS-Settings#29]
Thanks for your work, I just test your settings on my Fedora 38 systems.
While I copy the various config files I think of writing a small ansible playbook. I think this would be helpful for some people.

Maybe I file a PR as soon as I find the time to write a playbook.

**Comment by ptr1337** [comment]
> Thanks for your work, I just test your settings on my Fedora 38 systems. While I copy the various config files I think of writing a small ansible playbook. I think this would be helpful for some people.
> 
> Maybe I file a PR as soon as I find the time to write a playbook.

Hi,
We can welcome this. We could also create a COPR repository to provide these settings.
For other distro's this would also work.

**Comment by sirlucjan** [comment]
We have COPR already: https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/

If you send a PR I will be happy to add it.

**Comment by 1Naim** [comment]
This issue has staled so I'm closing it. Feel free to reopen it.
