### ISSUE TITLE
I think NVreg_DynamicPowerManagement should be disabled.

### ISSUE THREAD

**Issue by Boria138** [CachyOS/CachyOS-Settings#32]
I personally haven't had a chance to test it, but according to the developer of envycontrol

 ```
Minuses: poor battery life on cards that don't support dynamic power management (like mine), external screens are laggy due to X.org's non-functional reverse PRIME implementation, and Wayland crashes when an external screen is connected (tested on Gnome).
```
I also personally have an unpleasant bug, if you switch envycontrol from hybrid to Nvidia mode the system does not show pictures, just a blank black screen, I have not yet determined whether it is a bug of Nvidia tweaks in cachyos or envycontrol, but pay attention to it I think it's worth it

**Comment by ventureoo** [comment]
I don't consider these issues to be related to dynamic power management. NVIDIA itself includes dynamic power management in its RPM packages [1][2]. If it's as written here, it should affect Fedora users first and foremost. But I still haven't seen any bug reports related to this. Anyway, if it's an NVIDIA driver bug, you should point it out to them on their forum.

[1] - https://github.com/NVIDIA/yum-packaging-nvidia-kmod-common/blob/main/nvidia.conf#L16
[2] - https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia.conf#L22
