### ISSUE TITLE
CachyOS settings are not compatible with EnvyControl

### ISSUE THREAD

**Issue by Boria138** [CachyOS/CachyOS-Settings#33]
When trying to switch from hybrid graphics to Nvidia mode, the system stops booting and hangs on a black screen. I uninstalled the settings from CachyOS and the system started booting fine, but hibernation stopped working. Adding the CachyOS settings to EnvyControl solved the problem completely @ventureoo Since you wrote the settings for Nvidia in CachyOS, I would like to ask your permission to make a pr in EnvyControl using the settings from CachyOS to solve the hibernation problem

**Comment by ventureoo** [comment]
Yes, you can use it by specifying copyright of my nvidia-tweaks/CachyOS-Settings. But I don't use the different switches for Optimus/PRIME. I prefer to use the simple PRIME Offload used by default in the NVIDIA driver.

**Comment by Boria138** [comment]
Thanks for the permission, I would also advise you to write that envycontrol, optimus manager and other utilities that change modprobe and udev files for switching are not compatible with CachyOS.

**Comment by Boria138** [comment]
@ventureoo Looking through envycontrol errors I came across an interesting error according to which rtd3 in arch is broken I guess you will be interested to read it
https://github.com/bayasdev/envycontrol/issues/126
