### ISSUE TITLE
New IO scheduler settings

### ISSUE THREAD

**Issue by John-Gee** [CachyOS/CachyOS-Settings#34]
Hello,

I wondered if it would be good to investigate new IO settings based on: https://github.com/pop-os/default-settings/pull/149
While none is often recommended for nvme drives, is it really good on interactive devices or just on servers?

**Comment by John-Gee** [comment]
Do you know of any interesting happening around K2? https://github.com/TUD-OS/k2-scheduler/

**Comment by ptr1337** [comment]
Hi @John-Gee 

I have made a PR after 2 months of testing "kyber" on my nvme. I have created a PR for this.

The k2 scheduler seems really to be outdated and not worth to test or merge currently.

**Comment by John-Gee** [comment]
Thank you for looking into this!
