### ISSUE TITLE
Change /bin/sh to dash by default

### ISSUE THREAD

**Issue by lseman** [CachyOS/CachyOS-Settings#48]
As Arch Wiki, dash is faster, and could be used to replace /bin/sh in invocation scripts, and boot.

https://wiki.archlinux.org/title/Dash

**Comment by ptr1337** [comment]
> As Arch Wiki, dash is faster, and could be used to replace /bin/sh in invocation scripts, and boot.
> 
> https://wiki.archlinux.org/title/Dash

"Dash is not [Bash](https://wiki.archlinux.org/title/Bash) compatible, but Bash tries to be mostly compatible with POSIX, and thus Dash."

**Comment by lseman** [comment]
Yes, but it would be only for sh, not interactively stuff.
