### ISSUE TITLE
We should add a .urls file /etc/debuginfod

### ISSUE THREAD

**Issue by averms** [CachyOS/CachyOS-Settings#57]
Not sure if this is the right repository to report this but currently running `gdb` on my CachyOS installation doesn't download debug infos correctly. The fix is to add a cachyos.urls file in /etc/debuginfod next to the already existing archlinux.urls.

Should be implemented in a way that works for conversions from Arch.

**Comment by ptr1337** [comment]
https://github.com/CachyOS/CachyOS-Settings/pull/58

Could you please test, if it fixes the issue?

**Comment by ptr1337** [comment]
Its now rolled out to users (40-1) and should arrive also to the docker containers soon.

I will make also the weekend some updates to the docker containers and add also a v4 container.
