### ISSUE TITLE
[Feature] Consider putting config files under the .pacnew umbrella

### ISSUE THREAD

**Issue by Schlaefer** [CachyOS/CachyOS-Settings#60]
In my particular case I had an existing /etc/systemd/zram config which got overwritten by cachyos-settings.

Having the config files not being overwritten but instead in the .pacnew system would allow (the known) benefit of being notified about upstream changes while easily tweaking the local config.

Of course there are usually other ways to overrule any particular config, but this would neatly fit into Arch's established config update pattern.

**Comment by SoulHarsh007** [comment]
:wave: Have you considered using configuration overrides? I use this for my zram config:
![image](https://github.com/CachyOS/CachyOS-Settings/assets/57407752/9f3f7e2f-357c-44f2-b619-ab76ab1f35d4)
and it works just fine. You should be using overrides, as marking files as backup prevents us from making crucial changes which might impact performance.
