### ISSUE TITLE
should zram or zswap be used when diskswap or swapfile exists?

### ISSUE THREAD

**Issue by leonpano2006** [CachyOS/CachyOS-Settings#67]
for me on fedora `cachyos-settings` depends on `zram-generator`
but kernel have zswap enabled on default(not self compiled, i use form copr repo)

**Comment by ptr1337** [comment]
> for me on fedora `cachyos-settings` depends on `zram-generator` but kernel have zswap enabled on default(not self compiled, i use form copr repo)

The cachyos-settings package is intended for cachyos and its defaults. We do not provide a swap option and zram is used as default.
You would need to disable zswap and should give the niormal swap a lower priority then zram
