### ISSUE TITLE
Nvidia GSP making SteamVR unplayable

### ISSUE THREAD

**Issue by joni999** [CachyOS/CachyOS-Settings#73]
Hi!
Not sure if this is the correct place, but I noticed that there are issues with heavy stuttering / framedrops in VR (only inside the VR headset - I'm using Valve Index) only with Nvidia's GSP enabled.

I'll report this on Nvidia's Forums as well. This is more of an "FYI" Post
GSP enabled:
![SteamVR shenanigans](https://github.com/CachyOS/CachyOS-Settings/assets/58270144/ce3d623b-1e09-4fc3-9a00-fcce83692cbf)
The purple lines in the performance graph are "Display Error"

GSP disabled:
![SteamVR before update no issues](https://github.com/CachyOS/CachyOS-Settings/assets/58270144/57876c86-7497-4b91-bce5-f94cdadce393)

**Comment by ptr1337** [comment]
> Hi! Not sure if this is the correct place, but I noticed that there are issues with heavy stuttering / framedrops in VR (only inside the VR headset - I'm using Valve Index) only with Nvidia's GSP enabled.
> 
> I'll report this on Nvidia's Forums as well. This is more of an "FYI" Post GSP enabled: ![SteamVR shenanigans](https://private-user-images.githubusercontent.com/58270144/346212666-ce3d623b-1e09-4fc3-9a00-fcce83692cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTYxNzQsIm5iZiI6MTcyMDIxNTg3NCwicGF0aCI6Ii81ODI3MDE0NC8zNDYyMTI2NjYtY2UzZDYyM2ItMWUwOS00ZmMzLTlhMDAtZmNjZTgzNjkyY2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIxNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjN2VhMzRhYTdjMTZkMTg4ZWM5OWFkNGQwNDA1MmU2OWVmZTFmYWM0NzkyMzY2NGYyZjZlOTFhZDViZTc3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nA2Xz0sY3MPIaRdQCWC3O3yz4zVnT8C_ozwXC04kGfw) The purple lines in the performance graph are "Display Error"
> 
> GSP disabled: ![SteamVR before update no issues](https://private-user-images.githubusercontent.com/58270144/346212690-57876c86-7497-4b91-bce5-f94cdadce393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTYxNzQsIm5iZiI6MTcyMDIxNTg3NCwicGF0aCI6Ii81ODI3MDE0NC8zNDYyMTI2OTAtNTc4NzZjODYtNzQ5Ny00YjkxLWJjZTUtZjk0Y2RhZGNlMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIxNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMGZmYjM4NzhmN2JlY2VkNWIwZDNmNTgxYmUxODhiZTM1ZTdlNGM4ODZmMjE2OTlmOTkxMmI1YWRmYTJiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fewOgrZmvE2HuTOz-DSVhR8hYgsM9jJ0sbErSxlwAIM)

I would suggest you disabling it manually for now, as noted here:
https://wiki.cachyos.org/configuration/general_system_tweaks/#9-nvidia-gsp-firmware

We will keep GSP enabled for now.

**Comment by joni999** [comment]
I can live with that, thanks!
