### ISSUE TITLE
[RFC] Use systemd-resolved with NetworkManager by default

### ISSUE THREAD

**Issue by vnepogodin** [CachyOS/CachyOS-Settings#79]
Using systemd-resolved will help with caching of dns requests, making steam downloads faster. While NetworkManager still manage other network stack.

Additionally fixes compatibility with some VPN apps which want to use resolved

requires `systemd-resolved.service` to be enabled

ref: https://wiki.archlinux.org/title/NetworkManager#systemd-resolved

**Comment by 1Naim** [comment]
There were discussions a while back to consider [dnsproxy](https://github.com/AdguardTeam/dnsproxy) instead. Did it fall short in terms of features provided, e.g. ECH not supported, or do you think its better to use something thats already installed as default?

**Comment by vnepogodin** [comment]
> There were discussions a while back to consider [dnsproxy](https://github.com/AdguardTeam/dnsproxy) instead. Did it fall short in terms of features provided, e.g. ECH not supported, or do you think its better to use something thats already installed as default?

Yeah there were also discussions about not using networkmanager at all, in favor of systems stack. Generally some software expects resolved for setting system DNS(like VPN) and fails its not present. Using resolved also doesnt require us to install additional package. For using ECH and DoH, we can just conditionally install it by Welcome app
