### ISSUE TITLE
game-performance wrapper script under flatpak environment

### ISSUE THREAD

**Issue by PopCat19** [CachyOS/CachyOS-Settings#89]
Is it possible to use the wrapper script `game-performance` within a flatpak environment? 
|
`cachyos-gaming-meta` is installed, and it works on lutris native. I enabled host overrides within flatseal:
![image](https://github.com/user-attachments/assets/d0bee160-3576-4952-9e98-8f0a234843b2)

**Comment by ptr1337** [comment]
It should work, yes.
