### ISSUE TITLE
apparmor filesystem is not mounted

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/CachyOS-Settings#96]
I was checking out apparmor, and it seemed to be inactive and not working properly.

`sudo systemctl status apparmor.service`

I tried enabling `sudo systemctl enable --now apparmor.service` and got this `Load AppArmor profiles was skipped because of an unmet condition check (ConditionSecurity=apparmor)`

Then I run the status and got this.
```
> sudo aa-status
apparmor module is loaded.
apparmor filesystem is not mounted.
```

` /sys/module/apparmor/parameters/enabled` was returning `N`

And the suggested fix seem to be adding this to kernel bootline `apparmor=1 lsm=lockdown,yama,apparmor`

This might need to be checked on cachyos, as I only have added those two lines to the configuration and yet.

**Comment by vnepogodin** [comment]
yeah we have guide how to enable & setup apparmor https://wiki.cachyos.org/configuration/post_install_setup/#4-enable-apparmor-support-using-apparmord-profiles

**Comment by ptr1337** [comment]
See: https://wiki.cachyos.org/configuration/post_install_setup/#4-enable-apparmor-support-using-apparmord-profiles

**Comment by dougg0k** [comment]
Your server might be overloaded, second website from you that are very slow to load.
![Screenshot from 2024-09-30 16-51-37](https://github.com/user-attachments/assets/5c378184-8575-4051-8910-cb74ec9e99b0)

**Comment by ptr1337** [comment]
> Your server might be overloaded, second website from you that are very slow to load. ![Screenshot from 2024-09-30 16-51-37](https://private-user-images.githubusercontent.com/10801221/372225785-5c378184-8575-4051-8910-cb74ec9e99b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MjY3NDUsIm5iZiI6MTcyNzcyNjQ0NSwicGF0aCI6Ii8xMDgwMTIyMS8zNzIyMjU3ODUtNWMzNzgxODQtODU3NS00MDUxLTg5MTAtY2I3NGVjOWU5OWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIwMDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZjQ5NWY1ZTliYjQ3NDUyN2I4ZGEzY2Q3ZjJlYWNlMTI0NjIyNTA4N2YzMWJlNjQ4NGI1MDc1OGYxZGM2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lYfZKzCQj918L3Cigrbhf8KU3Lt1ziN8DkBjTp__TqU)

This content is delivered by cloudflare and their cache servers, since its static content. You might want to check your ISPs routing
