### ISSUE TITLE
AMD improve 1% lows and avg fps

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/CachyOS-Settings#99]
https://github.com/hyprwm/Hyprland/issues/2085#issuecomment-1534398232

https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_825883

I dont have AMD GPU to test.

**Comment by vnepogodin** [comment]
well, would like to have it confirmed on KDE/GNOME

**Comment by 1Naim** [comment]
> well, would like to have it confirmed on KDE/GNOME

https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_2583767 The latest comment on the same thread confirms that it is still happening on KDE.

**Comment by 1Naim** [comment]
At least with https://github.com/CachyOS/linux/commit/270c777963bab2823ea0246e35b7a73825ffafee, profile should default to `3D_FULLSCREEN` now for dGPUs. I'm hesitant to force performance level to high or manual (apparently its needed for VRR to work correctly on RDNA2), it just seems like a very dirty way to fix things. I'll consider this issue half-fixed and close it.
